version: 2.1

jobs:

  deploy_dev:
    docker:
      - image: cimg/android:2023.12.1
    steps:
      - checkout
      - run:
          name: Store Google Services Key
          command: echo $GOOGLE_SERVICES_KEY_DEV | base64 -di > app/google-services.json
      - run:
          name: configure build
          command: sudo bundle install
      - run:
          name: "Install Firebase CLI"
          command: curl -sL firebase.tools | bash
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run:
          name: "Deploy dev build to Firebase"
          command: bundle exec fastlane beta branch:${CIRCLE_BRANCH} app_id:${FIREBASE_APP_ID_DEV} firebase_token:$FIREBASE_TOKEN

workflows:
  build_tests_deploy:
    jobs:
      - deploy_dev
