# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Increment version code"
  lane :increment_vc do
    increment_version_code(
      gradle_file_path: "./gradle/libs.versions.toml",
      ext_constant_name: "versionCode",
    )
  end

  desc "Runs all the tests"
  lane :test_debug do
    gradle(
      task: "test",
      build_type: "debug"
    )
  end

  desc "Run lint"
  lane :lint_debug do
    gradle(
      task: "lint",
      build_type: "debug"
    )
  end

  desc "Run detekt"
  lane :detekt_debug do
    gradle(
      task: "detekt",
      build_type: "debug"
    )
  end

  desc "Build debug"
  lane :build_debug do
    gradle(
      task: "assemble",
      build_type: "debug --scan"
    )
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do |options|
    increment_vc
    build_debug

    firebase_app_distribution(
      app: "#{options[:app_id]}",
      groups: "developers",
      apk_path: "app/build/outputs/apk/debug/app-debug.apk",
      firebase_cli_token: "#{options[:firebase_token]}"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
