# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Increment version code"
  lane :increment_vc do
    increment_version_code(
      gradle_file_path: "./gradle/libs.versions.toml",
      ext_constant_name: "versionCode",
    )
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build debug"
  lane :build_debug do
    gradle(
      task: "assemble",
      build_type: "debug"
    )
  end

  desc "Submit a new Beta Build to Firebase App Distribution"
  lane :beta do
    increment_vc
    build_debug

    firebase_app_distribution(
      app: "1:783268528847:android:92a89cafade2599a8e6dba",
      groups: "developers"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
