package nikitafrolov.designsystem.theme

import androidx.compose.ui.graphics.Color

val lightPrimary = Color(0xFF6750A4)
val lightOnPrimary = Color(0xFFFFFFFF)
val lightPrimaryContainer = Color(0xFFE9DDFF)
val lightOnPrimaryContainer = Color(0xFF22005D)
val lightSecondary = Color(0xFF625B71)
val lightOnSecondary = Color(0xFFFFFFFF)
val lightSecondaryContainer = Color(0xFFE8DEF8)
val lightOnSecondaryContainer = Color(0xFF1E192B)
val lightTertiary = Color(0xFF00629E)
val lightOnTertiary = Color(0xFFFFFFFF)
val lightTertiaryContainer = Color(0xFFCFE5FF)
val lightOnTertiaryContainer = Color(0xFF001D34)
val lightError = Color(0xFFBA1A1A)
val lightErrorContainer = Color(0xFFFFDAD6)
val lightOnError = Color(0xFFFFFFFF)
val lightOnErrorContainer = Color(0xFF410002)
val lightBackground = Color(0xFFFFFBFF)
val lightOnBackground = Color(0xFF1C1B1E)
val lightSurface = Color(0xFFFFFBFF)
val lightOnSurface = Color(0xFF1C1B1E)
val lightSurfaceVariant = Color(0xFFE7E0EB)
val lightOnSurfaceVariant = Color(0xFF49454E)
val lightOutline = Color(0xFF7A757F)
val lightInverseOnSurface = Color(0xFFF4EFF4)
val lightInverseSurface = Color(0xFF313033)
val lightInversePrimary = Color(0xFFCFBCFF)
val lightShadow = Color(0xFF000000)
val lightSurfaceTint = Color(0xFF6750A4)
val lightOutlineVariant = Color(0xFFCAC4CF)
val lightScrim = Color(0xFF000000)

val darkPrimary = Color(0xFFCFBCFF)
val darkOnPrimary = Color(0xFF381E72)
val darkPrimaryContainer = Color(0xFF4F378A)
val darkOnPrimaryContainer = Color(0xFFE9DDFF)
val darkSecondary = Color(0xFFCBC2DB)
val darkOnSecondary = Color(0xFF332D41)
val darkSecondaryContainer = Color(0xFF4A4458)
val darkOnSecondaryContainer = Color(0xFFE8DEF8)
val darkTertiary = Color(0xFF99CBFF)
val darkOnTertiary = Color(0xFF003355)
val darkTertiaryContainer = Color(0xFF004A78)
val darkOnTertiaryContainer = Color(0xFFCFE5FF)
val darkError = Color(0xFFFFB4AB)
val darkErrorContainer = Color(0xFF93000A)
val darkOnError = Color(0xFF690005)
val darkOnErrorContainer = Color(0xFFFFDAD6)
val darkBackground = Color(0xFF1C1B1E)
val darkOnBackground = Color(0xFFE6E1E6)
val darkSurface = Color(0xFF1C1B1E)
val darkOnSurface = Color(0xFFE6E1E6)
val darkSurfaceVariant = Color(0xFF49454E)
val darkOnSurfaceVariant = Color(0xFFCAC4CF)
val darkOutline = Color(0xFF948F99)
val darkInverseOnSurface = Color(0xFF1C1B1E)
val darkInverseSurface = Color(0xFFE6E1E6)
val darkInversePrimary = Color(0xFF6750A4)
val darkShadow = Color(0xFF000000)
val darkSurfaceTint = Color(0xFFCFBCFF)
val darkOutlineVariant = Color(0xFF49454E)
val darkScrim = Color(0xFF000000)

val seed = Color(0xFF6750A4)